### ISSUE TITLE
Game not starting

### ISSUE THREAD

**Issue by quantumech3** [dyscott/home-guesser#1]
When I load your webpage, nothing shows by default. Things are pretty well documented though so I was able to find the issues pretty quickly :). Im guessing the expected behavior is that it shows a map and a zillow website and starts the game automatically. This is what I see when I load the page though. There are no errors in the console.

![image](https://user-images.githubusercontent.com/22784607/129937116-a7a265ae-1bda-4d63-a875-cabd547446c3.png)

I was able to make the map show by invoking `initMap()` in the debug console. As for the Zillow houses themself, I think I may have found the problem: your getting a captcha instead of an image when you load a zillow webpage lol.
![image](https://user-images.githubusercontent.com/22784607/129937640-892f8762-6aa7-4eff-a804-da4332265051.png)

Zillow clearly does not like people scraping their site, so perhaps you could use the Zillow API instead? https://www.zillow.com/howto/api/APIOverview.htm

**Comment by dyscott** [comment]
Resolved in commit 765efad
